library(tidyverse)

# Expanded metadata table
survey_meta <- tribble(
  ~Section, ~QID, ~Type, ~Base, ~Question,
  "A", "QA_Intro", "Info screen", "Ask All", "We would ﬁrst like to ask about your experiences of being a member of WERC, and the impact it has had on you.",
  "A", "QA_1", "Single Code", "Ask All", "How long have you been a member of WERC?",
  "A", "QA_2", "Single Code", "Ask All", "How did you ﬁnd out about WERC?",
  "A", "QA_3", "OE Long text", "Ask All", "What have you enjoyed about being a member?",
  "A", "QA_4", "Multicode max 3", "Ask All", "Thinking about the beneﬁts that you have experienced being a member of WERC - what have been your top 3?",
  "A", "QA_5", "OE Long text", "Ask All", "Is there anything that we could do to further enhance your feeling safe within the club?",
  "A", "QA_6", "OE Long text", "Ask All", "Is there anything that you feel could be done to improve your overall experience?",
  "A", "QA_7", "OE Long text", "Ask All", "Are there any special memories or highlights from being involved in the club you would like to share with us?",
  "A", "QA_8", "OE Long text", "Ask All", "What impact has being a member of WERC had on you?",
  "B", "QB_Intro", "Info screen", "Ask All", "For this next set of questions, we would like you to think about all the different things the club offers for our members.",
  "B", "QB_1", "Multicode", "Ask All", "Which of the below club activities are you aware of?",
  "B", "QB_2", "Multicode", "Ask All", "Of these activities, which ones have you participated in?",
  "B", "QB_3", "Multicode", "Ask All", "And which of these activities do you intend to participate in sometime in the future?",
  "B", "QB_4", "OE Long text", "Ask All", "Is there anything that we do not currently offer that you would like to see more of?",
  "C", "QC_Intro", "Info screen", "Ask All", "For this group of questions we would like you to think about our main Thursday night training sessions",
  "C", "QC_1", "Single code", "Ask All", "Have you ever participated in one of our Thursday night training sessions?",
  "C", "QC_2_1", "Single code grid; randomise statement order", "Ask all coding QC_1 = 1", "The variety of Thursday night sessions offered across the year",
  "C", "QC_2_2", "Single code grid; randomise statement order", "Ask all coding QC_1 = 1", "How enjoyable you find the sessions",
  "C", "QC_2_3", "Single code grid; randomise statement order", "Ask all coding QC_1 = 1", "How appropriate and relevant the sessions are to your own running / training",
  "C", "QC_2_4", "Single code grid; randomise statement order", "Ask all coding QC_1 = 1", "How approachable you find the coaching team",
  "C", "QC_2_5", "Single code grid; randomise statement order", "Ask all coding QC_1 = 1", "The quality of the coaching team and their delivery of sessions",
  "C", "QC_2_6", "Single code grid; randomise statement order", "Ask all coding QC_1 = 1", "The professionalism and knowledge of the coaching team",
  "C", "QC_2_7", "Single code grid; randomise statement order", "Ask all coding QC_1 = 1", "How easy it is to understand what the session is and what you need to do",
  "C", "QC_3", "OE Long text", "Ask All", "Is there anything you feel your coaching team is doing particularly well?",
  "C", "QC_4", "OE Long text", "Ask All", "And is there anything you feel your coaching team could improve on?",
  "D", "QD_Intro", "Info screen", "Ask All", "At WERC, we want to ensure we continually meet the needs of our membership today and long into the future. The next few questions will help us better understand your thoughts on how we might organise the club in the future.",
  "D", "QD_1", "Single code", "Ask All", "What would be your preferred group size for a typical Thursday night session?",
  "D", "QD_2", "Single code", "Ask All", "How far would you be willing to travel to a session?",
  "D", "QD_3", "Multicode", "Ask All", "If we were to split our main Thursday session into smaller groups of runners, which of the following options would you feel comfortable with?",
  "D", "QD_4", "Single code", "Ask All", "And which would be your preferred way to split our main Thursday session?",
  "D", "QD_5", "Single code", "Ask All", "How interested would you be in a 'social run' option as well as our typical interval offering on a Thursday night?",
  "E", "QE_Intro", "Info screen", "Ask All", "In this section, we would like to get your thoughts on our values and how we are adhering to these as a club",
  "E", "QE_1_1", "OE Long text", "Ask All", "Inclusivity",
  "E", "QE_1_2", "OE Long text", "Ask All", "Community",
  "E", "QE_1_3", "OE Long text", "Ask All", "Quality",
  "E", "QE_2", "Single code", "Ask All", "Below is a graphic showing our WERC club values. To what extent do you think we are displaying those values?",
  "E", "QE_3", "OE Long text", "Ask All", "Why do you think this? Is there anything else we could be doing to further display our values?",
  "E", "QE_4", "Single code", "Ask All", "Are you aware of who our welfare officer is, and how to contact them?",
  "F", "QF_Intro", "Info screen", "Ask All", "For the next few questions we would like to get your thoughts on how we communicate what is going on at West Edinburgh Running Club with you",
  "F", "QF_1", "Multicode", "Ask All", "Which of the below communication channels do you use to find out information about the Club?",
  "F", "QF_2", "Single code", "Ask All", "And which of these is the main way you find out what is going on?",
  "F", "QF_3_1", "Single code grid; randomise statement order", "Ask all coding QC_1 = 1", "The timeliness of information being released",
  "F", "QF_3_2", "Single code grid; randomise statement order", "Ask all coding QC_1 = 1", "The clarity of our comms",
  "F", "QF_3_3", "Single code grid; randomise statement order", "Ask all coding QC_1 = 1", "The amount of comms activity",
  "F", "QF_3_4", "Single code grid; randomise statement order", "Ask all coding QC_1 = 1", "How easy it is to access and find information about the club and its activities",
  "F", "QF_4", "OE Long text", "Ask All", "And do you have any suggestions on how we could improve the way we communicate with you?",
  "G", "QG_Intro", "Info screen", "Ask All", "We are keen to understand the reach of the club and how different people experience being a member.",
  "G", "QG_1", "Single code", "Ask All", "What is your age?",
  "G", "QG_2", "Single code", "Ask All", "What is your gender?",
  "G", "QG_3", "Single code", "Ask All", "What is your ethnic group?",
  "G", "QG_4", "Single code", "Ask All", "Approximately how far do you travel to reach our main training location, Saughton Park?",
  "G", "QG_5", "OE Long text", "Ask All", "Is there anything we could do further to improve accessibility for all?",
  "G", "QG_6", "OE Long text", "Ask All", "And finally, are there any other suggestions or comments you would like to share for your WERC committee to consider?"
)

# Save as CSV
write_csv(survey_meta, "data/survey_metadata_expanded.csv")